# Configuration des registres cibles et de l'ordre de recherche
unqualified-search-registries = ["docker.io", "ghcr.io", "quay.io"]

[[registry]]
name = "docker-hub"
location = "docker.io"

[[registry]]
name = "github-packages"
location = "ghcr.io"

[[registry]]
name = "quay"
location = "quay.io"
