Port 42022
AddressFamily any
UseDNS yes
PubkeyAuthentication yes
PasswordAuthentication no
PermitEmptyPasswords no
PermitRootLogin no
MaxAuthTries 3
ChallengeResponseAuthentication no
UsePAM no
AllowAgentForwarding no
X11Forwarding no
IgnoreRhosts yes
AuthenticationMethods publickey
AllowTcpForwarding no
DisableForwarding yes
ForceCommand none
GatewayPorts no
